server:
  port: 8761
  
spring:
  application:
    name: eureka-server
  config:
    import:
    - "optional:configserver:http://root:root@localhost:8672/application.yml"
  security:
    user:
      name: root
      password: root

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    renewal-threshold-update-interval-ms: 1000
  instance:
    hostname: localhost