server:
  port: 8672

spring:
  security:
    user:
      name: root
      password: root
  application:
    name: park-config-server
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          default-label: main
          username: xxxxx
          password: xxxxx
          uri: git@github.com:kowsuram/park-config.git
          
management:
  endpoint:
    refresh:
      enabled: true
