server:
  port: 8672

spring:
  application:
    name: park-config-server
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          default-label: main
          username: xxxxxx
          password: xxxxxx
